### PR TITLE
Fix #24: NPE when dependencyManagement undefined and a signature is unresolvable

### LINKED ISSUE #24: NPE from CheckSignatureMojo.execute
I am getting

```
java.lang.NullPointerException
	at org.codehaus.mojo.animal_sniffer.maven.CheckSignatureMojo.execute(CheckSignatureMojo.java:211)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
```

when trying to run Animal Sniffer on a new project, even though (AFAIK) I have no improper APIs being used.

[Here](https://github.com/mojohaus/animal-sniffer/blob/animal-sniffer-parent-1.15/animal-sniffer-maven-plugin/src/main/java/org/codehaus/mojo/animal_sniffer/maven/CheckSignatureMojo.java#L211) is the faulty line of code:

```java
match = findMatchingDependency( signature, project.getDependencyManagement().getDependencies() );
```

Effective POM excerpt:

```xml
<plugin>
  <groupId>org.codehaus.mojo</groupId>
  <artifactId>animal-sniffer-maven-plugin</artifactId>
  <version>1.15</version>
  <executions>
    <execution>
      <id>check</id>
      <goals>
        <goal>check</goal>
      </goals>
      <configuration>
        <signature>
          <groupId>org.codehaus.mojo.signature</groupId>
          <artifactId>java17</artifactId>
        </signature>
      </configuration>
    </execution>
  </executions>
  <configuration>
    <signature>
      <groupId>org.codehaus.mojo.signature</groupId>
      <artifactId>java17</artifactId>
    </signature>
  </configuration>
</plugin>
```

### PR DESCRIPTION
**Pull request by jglick**
Fixes #24.

@reviewbybees for my colleagues esp. @stephenc who I think introduced this code

### CODE REVIEW

**Comment by jglick** [comment]
Could not transfer artifact org.ow2.asm:asm-analysis:jar:5.0.1 from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.32.215] failed: Connection timed out

**Comment by stephenc** [comment]
:bee:

**Comment by jglick** [comment]
@reviewbybees done

**Comment by rfscholte** [comment]
No test?

**Comment by jglick** [comment]
CI failures seem unrelated:

    Connect to repository.apache.org:443 [repository.apache.org/207.244.88.143] failed: Connection timed out

**Comment by jglick** [comment]
Ping @rfscholte?

**Comment by jglick** [comment]
Seems to have integrated as cf5c5ff9ed010a0b991245dda69a9fe911ba33d0 + 590c5dd885ea0cc71bd17a3aa86a02ff61db43de.

**Pull request closed without merging**
