### PR TITLE
#41 - Correctly validate the type of the exceptions caught in try...catch blocks

### PR DESCRIPTION
**Pull request by csoroiu**

### CODE REVIEW

**Comment by csoroiu** [comment]
i've rebased the fix for #41 to latest code. The build fails because the maven wrapper plugin was released recently and seems to be built with java 8, thus all the java 7 builds are failing.

**Comment by csoroiu** [comment]
I rebased it. The PR passes all the tests.
Thanks

**Comment by csoroiu** [comment]
I rebased it again. The PR passes all the tests.

**Comment by olamy** [comment]
Too many changes are not related to the subject. Please limit to only your issue.

**Comment by csoroiu** [comment]
I left only the changeset addressing #41.
Thanks

**Pull request merged**
