### PR TITLE
#41 - Correctly validate the type of the exceptions caught in try...catch blocks

### PR DESCRIPTION
**Pull request by csoroiu**

### CODE REVIEW

**Comment by csoroiu** [comment]
same as yesterday, the build fails for jdk7, apparently that is an issue with travis caches

**Comment by tchemit** [comment]
I just try this MR on master and all is green \o/

**Comment by csoroiu** [comment]
I'll close and reopen de PR. 
Thanks

**Comment by csoroiu** [comment]
The reopened PR (#47) passed the checks.

**Pull request closed without merging**
